### ISSUE TITLE
Row count at the top of every list

### ISSUE THREAD

**Issue by charles-thompson-salesforce-com** [SalesforceLabs/OrgCheck#115]
**Is your feature request related to a problem? Please describe.**
OrgCheck helps me greatly with my org review report.  I need to summarise the technical debt faced by the customer.  I can get the row count easily by exporting to CSV then using Excel to show the row count.  BUT it would be so much nicer to have OrgCheck show it at the top of every list.

**Describe the solution you'd like**
- Row count at the top (or bottom) of every list
- Summary of all OrgCheck metadata components (+ row counts) on home page

**Describe alternatives you've considered**
- Export to CSV
- Chrome extension CopyTable, paste to Excel or Notepad++

**Additional context**

**Comment by VinceFINET** [comment]
Nice feature !!!
I am thinking of couple of different measures. 

- like the count of all the rows in the table, yes.
- But also the count of rows that have a bad score. 
- and maybe also the sum of all the scores. Why because somehow each +1 in a score means a task for the admin right

I will try to make a little mock for you and tell me if you are ok with that.

**Comment by VinceFINET** [comment]
Some screenshots

At start (without filter)
![image](https://user-images.githubusercontent.com/3799275/127978914-cac027ad-f0b1-45b5-8fc3-3247190e02f4.png)

After filtering
![image](https://user-images.githubusercontent.com/3799275/127979048-00204c9c-0c7b-4cd8-95a5-04013e67456b.png)

After removing filter
![image](https://user-images.githubusercontent.com/3799275/127979104-cb52d2bd-2356-45b2-b06e-ceea8ce73abc.png)

**Comment by charles-thompson-salesforce-com** [comment]
This is wonderful.  Thanks @VinceFINET !
