### ISSUE TITLE
 issue

### ISSUE THREAD

**Issue by phucao21** [SalesforceLabs/OrgCheck#140]
OrgCheck Information
Version: v1.9.6
Installed on OrgId: 00D7d0000077mQY

Navigation Information
Page: /apex/OrgCheck_ProfilesPermSets_VFP

System Information
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
Operating System: Win32
Language: en-US

Error #0: TypeError
Stack:
TypeError: Cannot read properties of undefined (reading 'id')
   at Object.onEnd (/resource/1641920052000/orgcheck__OrgCheck_OrgCheck_SR:3276:57)
   at /resource/1641920052000/orgcheck__OrgCheck_OrgCheck_SR:1730:38
   at /resource/1641920052000/orgcheck__OrgCheck_OrgCheck_SR:240:25

**Comment by VinceFINET** [comment]
Hi @phucao21 

Thank you for providing this error stack!

From the Stack Trace, i can identify that the issue is the following:
- Your org has Permission Set Groups
- OrgCheck is listing the permission set groups by looking into two tables: 
   - PermissionSet (with IsOwnedByProfile = FALSE and Type = 'Group)
   - PermissionSetGroup (all)
- It seems that in your case a specific permission set group was found in PermissionSet table and not in the PermissionSetGroup

I am curious to find out is it specific to a permission set group that comes from a package or not...
Could we have a session together so that i can gather more information to reproduce and resolve this issue?

Thank you
Vincent

**Comment by phucao21** [comment]
Hi Vincent.

sure, please send me the meeting invite.

-Phu

**Comment by VinceFINET** [comment]
Hi @phucao21

Could you post here the result of the two following queries (not using tooling api):

Query 1: 
```
SELECT Id, Name, IsCustom, NamespacePrefix, Type
FROM PermissionSet
WHERE IsOwnedByProfile = FALSE
```
(and filter only the ones that have Type='Group' (for some reason the filter in SOQL is not working)

Query 2: 
```
SELECT Id, DeveloperName, Description, NamespacePrefix, Status 
FROM PermissionSetGroup
```

The error might be linked to the fact that the permission set group have a Name in query 1 different from the DeveloperName in query 2.

Thank you

**Comment by VinceFINET** [comment]
On my side I have:

Query 1:
![image](https://user-images.githubusercontent.com/3799275/151977769-81bf6ab2-47a1-4a9c-b380-6ef6509a0321.png)

Query 2:
![image](https://user-images.githubusercontent.com/3799275/151977875-d46e0d8e-1c37-4b38-a741-65d0bc023fdb.png)

The error you have is happening because a permission set group in Query 1 is not found in Query 2 (based on the key = Namespace + '-' + Name/DeveloperName)

**Comment by VinceFINET** [comment]
Duplicate of #176
