### ISSUE TITLE
no-namespace unlocked packages are not listed

### ISSUE THREAD

**Issue by elex3nda** [SalesforceLabs/OrgCheck#215]
I would expect that at least the contents of no-namespace unlocked packages (if not all unlocked packages) are listed with the APEX classes. I however cannot find them and don't know what could be the explanation. 

Best regards

**Comment by VinceFINET** [comment]
Hi @elex3nda 

The query that retrieves the ApexClass records is the following (from the Tooling API):

```
SELECT Id, Name, ApiVersion, NamespacePrefix, 
  Body, LengthWithoutComments, SymbolTable, 
  CreatedDate, LastModifiedDate 
FROM ApexClass 
WHERE ManageableState = 'unmanaged'
```

According to me the Apex classes that are in your org, from an unlocked package with or without a namespace, should be listed with the previous query.
Because the unlocked package is not "managed" according to me.
But I could definitely be mistaken.

If I am wrong would it be possible for you to do the following query with an Apex Class of your choice that according to you SHOULD be part of the list? and adding in the column "ManageableState" so i can see what 's wrong.

Something like (change the Id of course!!):

```
SELECT Id, Name, ApiVersion, NamespacePrefix, 
  Body, LengthWithoutComments, SymbolTable, 
  CreatedDate, LastModifiedDate, ManageableState 
FROM ApexClass 
WHERE Id = 'abcdefghijklmnopqrstuvwxyz'
```

And paste here the result of the query?

Thank you in advance.
Vincent

**Comment by elex3nda** [comment]
Hi Vincent,

I did some testing. 'unmanaged' doesn't fetch unlocked/no-namespace. Those
are 'installedEditable' as it seems. The following seems to work to fetch
both:

SELECT Id, Name, ApiVersion, NamespacePrefix,
  Body, LengthWithoutComments, SymbolTable,
  CreatedDate, LastModifiedDate
FROM ApexClass
WHERE ManageableState = 'installedEditable' OR ManageableState = 'unmanaged'

Best Regards
Alex

Am Do., 8. Dez. 2022 um 19:24 Uhr schrieb Vincent FINET <
***@***.***>:

**Comment by VinceFINET** [comment]
perfectly clear!

So i will update all queries from:
```
WHERE ManageableState = 'unmanaged'
```
to:
```
WHERE ManageableState IN ('installedEditable', 'unmanaged') 
```
