### ISSUE TITLE
Ran into OrgCheck error!

### ISSUE THREAD

**Issue by michaelguse** [SalesforceLabs/OrgCheck#218]
Please go [here](https://github.com/VinceFINET/OrgCheck/issues) and log an issue with the following information.

Salesforce Information
Salesforce API Version: 56
Installed on OrgId: 00D7h0000004huo
Type of this org: Sandbox
Current running UserId: 0057h0000044ybMAAQ
Current Daily Api Requests: {"Max":16135600,"Remaining":16133900}

Navigation Information
Page: /apex/OrgCheck_PublicGroups_VFP

System Information
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language: en-US

Issue #0: ERROR_HTTP_400
When: While creating a promise to call a SOQL query.
What:
index: 0
queryMore: undefined
queryString: SELECT Id, Name, DeveloperName, DoesIncludeBosses, Type, RelatedId, Related.Name, (SELECT UserOrGroupId From GroupMembers)FROM Group
queryUseTooling: undefined
Stack:
ERROR_HTTP_400: Access Declined
   at r.getError (/resource/1661961641000/orgcheck__OrgCheck_SR/js/jsforce.js:1:72641)
   at /resource/1661961641000/orgcheck__OrgCheck_SR/js/jsforce.js:1:71009
   at /resource/1661961641000/orgcheck__OrgCheck_SR/js/jsforce.js:1:229622
   at /resource/1661961641000/orgcheck__OrgCheck_SR/js/jsforce.js:1:229650
   at MutationObserver.o (/resource/1661961641000/orgcheck__OrgCheck_SR/js/jsforce.js:1:104504)

**Comment by VinceFINET** [comment]
Thank you for raising this issue.

This 400 error with "Access Declined" is usually when Org Check is requesting the Salesforce API way too much.
But in your case, the query is a unique SOQL to the object "GROUP" which contains Public Groups and Queues.

What happens if you query directly using Developer Console (for example) without tooling api checked:
```
SELECT Id, Name, DeveloperName, DoesIncludeBosses, Type, RelatedId, Related.Name, 
         (SELECT UserOrGroupId From GroupMembers)
FROM Group 
```

Some questions:
- Do you have an error as well when querying ?
- How many Group records do you have?
- How many GroupMembers records do you have?

**Comment by VinceFINET** [comment]
Merging this ticket with #224
