### ISSUE TITLE
Object documentation tab - add more details

### ISSUE THREAD

**Issue by pritaunk** [SalesforceLabs/OrgCheck#28]
On the object documentation tab, I want to know

- if this object has regular scheduled updates / batch updates (this helps me identify is this object is being used in any of the integrations)
- which Salesforce profiles and permission sets have **View all** , **Delete** and **Modify** all permissions for this object
- bad score for an object would be when it is nearing 75% for custom fields, WFR, validation rule limit etc

**Comment by VinceFINET** [comment]
for your first point, it's going to be hard to check as I am only dealing with metadata and not data. And about the batches I have very few information about which sobject is used...

for your second point, it is interesting indeed to check that.
are you referring to ONLY the view all and modify all permission?
or also to Create, Update, Read and Delete permission?

for your last point, you need to have also a "bad score" on the object level. 
this is a nice idea because that tab did not have yet that notion.
some application are already doing this with gauge and all.
I'll try to see what can I do.

**Comment by pritaunk** [comment]
Great! for the 2nd point, yeah, if it can show all, even better as few of the objects might be high risk/confidential for an org where user profiles should not have any access, so yes it will be a useful piece of visibility!

**Comment by VinceFINET** [comment]
I added a flag for object limits 
Threshold is 75%

It will look like:
![image](https://user-images.githubusercontent.com/3799275/111223439-701ac000-85dd-11eb-9494-c05317ad5952.png)

**Comment by VinceFINET** [comment]
I have another tab about profiles that takes a lot of time when having to deal with 200 profiles.
let's put that CRUD in another issue to track this wonderful idea.
