### ISSUE TITLE
OrgCheck error message appearing for users without viewalldata access on Profile even though viewalldata is assigned via Permission set

### ISSUE THREAD

**Issue by leighjam** [SalesforceLabs/OrgCheck#341]
Hi there, Org Check team! I am trying to install the app for our Architects and due our company policy we cannot assign them the system admin profile. I have created a permission set that gives them access to org check and the view all data permission but every time they access org check they receive the following error message. They can ignore the error and org check still works for them but every time they do something they get this message. Is there a way around this message with out having to give their current assigned profile viewalldata?

![image](https://github.com/SalesforceLabs/OrgCheck/assets/78772951/be024a92-8f9c-49f4-808d-8fc833fd3b85)

**Comment by VinceFINET** [comment]
Thank you @leighjam for raising this issue.

Thanks to you, I discovered that this check is based on the Profile of the user and not on its assigned Permission Sets.
I will include this fix in Beryllium.
In the meantime, what you could do is to create a fresh sandbox for your production and give your user access to this sandbox and alter their profile (in this sandbox only) with the "see all data" system permission on.

I am sorry about the fact that it may not be the best solution for you, but in the meantime i can't deliver a fix in Lithium (v3) as I am in a final dev face to deliver Beryllium (v4).

But that will definitly be fixed in v4, let me assign this to this verison.

**Comment by leighjam** [comment]
Awesome thanks Vince!

**Comment by VinceFINET** [comment]
Watchdog implementation in Beryllium will be included in this issue.

**Comment by VinceFINET** [comment]
First the warning about exceeding the daily api should be on the org check api level and not on the UI level!!

**Comment by VinceFINET** [comment]
Second, the permissions check should be defined.

@leighjam 
can you make sure you have set the minimum system permissions for your users in your permission set:
 - `PermissionsModifyAllData`, 
 - `PermissionsAuthorApex`, 
 - `PermissionsApiEnabled`, 
 - `PermissionsViewAllUsers`

I think the best way would be (in the app) to check at first if (for the current user) the following query returns only true values.

```
SELECT PermissionsModifyAllData, PermissionsAuthorApex, PermissionsApiEnabled, PermissionsViewAllUsers 
FROM UserPermissionAccess
```

What do you think?

**Comment by VinceFINET** [comment]
need to add PermissionsManageSubscriptions as well (to query the table `InstalledSubscriberPackage`)

**Comment by VinceFINET** [comment]
need also the "PermissionsManageUsers" to get the last logins of users as well as profile and perm sets assignements.

**Comment by VinceFINET** [comment]
okay after testing a lot on my org I think that the permissions needed are (and their dependent permission as well):
- ModifyAllData
- AuthorApex
- ApiEnabled
- InstallPackaging

**Comment by VinceFINET** [comment]
the application will prompt something like this if your user has not the four permissions 
<img width="1202" alt="image" src="https://github.com/SalesforceLabs/OrgCheck/assets/3799275/d0887b43-48b5-4d50-9b32-4e8b492bc3af">
