### ISSUE TITLE
Object : Could not see details for Custom Object

### ISSUE THREAD

**Issue by jalal3107** [SalesforceLabs/OrgCheck#41]
Hello Vincent, 
Great job for OrgCheck.
We have noticed that when we displayed the detail of custom objects, no information are displayed.

<img width="1441" alt="image" src="https://user-images.githubusercontent.com/24570415/110004531-d3703c80-7d17-11eb-951e-c7f260eb7d10.png">
Could you please help to resolve this issue?
Best regards,

**Comment by VinceFINET** [comment]
I reproduced it in a sandbox.
--> The error occurs only when you are on "No Package" and when you select a custom object (standard object is OK).

Thank you for your feedback.

**Comment by VinceFINET** [comment]
**ENORME** as we say in French!!! you found a bug that was never found before.

The issue was that we were looking at the EntityDefinition (standard and custom object) in the tooling API with the wrong developer name.

In this use case the name of the object should not include the "__c" or "__mdt" or whatever comes at the end.
The fix is located in a method in javascript that does just that.

THANK YOU SO MUCH!
