### ISSUE TITLE
Cannot set properties of undefined (setting 'relatedClassIds')

### ISSUE THREAD

**Issue by jedevemy** [SalesforceLabs/OrgCheck#433]
**Describe the bug**
we can not get apex class information  and we get this error message 

TAB apex-classes TypeError: Cannot set properties of undefined (setting 'relatedClassIds')
TypeError: Cannot set properties of undefined (setting 'relatedClassIds')
at eval (https://popxxx--devxxxx--orgcheck.sandbox.vf.force.com/apex/modules/orgcheck/orgcheckApp.js:1:131448)

              
**To Reproduce**
we choose the apex tab, and we get the error
![image](https://github.com/user-attachments/assets/7175a2c4-288f-46bb-b504-f421f768af17)

**Comment by jedevemy** [comment]
This is in a sandbox,  summer 24,   service cloud & experience cloud,  user is admin.

**Comment by vfs-esrifrance** [comment]
Hi Vincent,
I have the same error on Sales cloud application in Production.
Best regards,
Vincent

**Comment by VinceFINET** [comment]
Thank you for your time log in this issue and comment this issue guys.

The issue is linked to this line of code:
https://github.com/SalesforceLabs/OrgCheck/blob/a539addd3668efa5e058341f6ec64d8e0c6a7a43/force-app/main/default/lwc/orgcheckApp/api/dataset/orgcheck-api-dataset-apexclasses.js#L167

The map that references ALL apex classes (including tests) do not include somehow the test class id....

The only root cause i could thing of is that the test class that covers the class are from a package or viiceversa...
Does it ring a bell to you?

**Comment by VinceFINET** [comment]
By the way, good catch you found a bug in the code, i need to send you an Org Check sticker. DM me your postal address or send me by email (but not here! obviously!!)

**Comment by VinceFINET** [comment]
The  relatedClassIds property in the code is used to show (obviously) the class that a unit test is covering (along with the percentage).

The error you have is when a class in your org is covered by an apex class unit test which is included in a managed package.

Now as we are not going to show the apex test classes from packages in the Org Check app, I believe this is correct to say that we could disregard that relation between a class and a managed test even if it's covering the class.
